



################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# copyright
copyright = "All Rights Reserved © 2022 Voucher Store Service Co., Ltd."



################################### Thai language #####################################
[th]
languageName = "Th"
languageCode = "th-th"
contentDir = "content/thai"
weight = 1
home = "หน้าหลัก"
# copyright
copyright = "All Rights Reserved © 2022 Voucher Store Service Co., Ltd."
